#!/bin/sh -l

#SBATCH --nodes=1                    ##number of requested nodes (a node is a group of CPUs)
#SBATCH -n 20                        ##number of requested CPUs
#SBATCH --time=04:00:00              ##time requested
#SBATCH --job-name Mouse_Import      ##name of job
#SBATCH -A microbiome                ##name of the queue you are using. Could be scholar or microbiome if you are on snyder

#########################################################################

echo "Start time"
date +"%d %B %Y %H:%M:%S"

cd $RCAC_SCRATCH
cd ANSC516_MouseData/picrust2_groups/Donor/

pwd

module use /depot/microbiome/apps/modulefiles
module load conda-env/qiime2-2021.11-py3.8.5

mkdir picrust2
cd picrust2

cp ../donor-filtered-table.qza .
cp ../rep-seqs.qza .

qiime picrust2 full-pipeline \
   --i-table donor-filtered-table.qza \
   --i-seq rep-seqs.qza \
   --output-dir q2-picrust2_output \
   --p-placement-tool sepp \
   --p-threads 4 \
   --p-hsp-method pic \
   --p-max-nsti 2 \
   --verbose

echo "End time"
date +"%d %B %Y %H:%M:%S"
