#!/bin/sh -l

#SBATCH --nodes=1                   
#SBATCH -n 20                        
#SBATCH --time=10:00:00              
#SBATCH --job-name Taxa-Fecal       
#SBATCH -A microbiome

echo "Start time"
date +"%d %B %Y %H:%M:%S"

cd $RCAC_SCRATCH
cd ANSC516_MouseData/Fecal

pwd

echo "loading bioinfo"
module load bioinfo

echo "loading qiime2-2023.9"
module load Qiime/2-2023.9

echo "initiating qiime2 taxonomy pipeline"

echo "Make a stacked barplot"
qiime taxa barplot \
  --i-table fecal-filtered-table.qza \
  --i-taxonomy taxonomy.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --o-visualization fecal-taxa-bar-plots.qzv

echo "Ancom"
qiime composition add-pseudocount \
  --i-table fecal-filtered-table.qza \
  --o-composition-table comp-fecal-table.qza
  
qiime composition ancom \
  --i-table comp-fecal-table.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --m-metadata-column donor_type \
  --o-visualization ancom-fecal-donor-type.qzv


echo "Collapse levels and ancom again."

qiime taxa collapse \
  --i-table fecal-filtered-table.qza \
  --i-taxonomy taxonomy.qza \
  --p-level 6 \
  --o-collapsed-table fecal-table-l6.qza

qiime composition add-pseudocount \
  --i-table fecal-table-l6.qza \
  --o-composition-table comp-fecal-table-l6.qza

qiime composition ancom \
  --i-table comp-fecal-table-l6.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --m-metadata-column donor_type \
  --o-visualization l6-ancom-fecal-donor-type.qzv



echo "End time"
date +"%d %B %Y %H:%M:%S"
