#!/bin/sh -l

#SBATCH --nodes=1                   
#SBATCH -n 20                        
#SBATCH --time=04:00:00              
#SBATCH --job-name Diversity-pipeline       
#SBATCH -A microbiome

echo "Start time"
date +"%d %B %Y %H:%M:%S"

cd $RCAC_SCRATCH
cd ANSC516_MouseData/Data_Import

pwd

echo "loading bioinfo"
module load bioinfo

echo "loading qiime2-2023.9"
module load Qiime/2-2023.9

echo "initiating qiime2 diversity pipeline"

echo "Create a phylogenetic tree. (Phylogenetic method)"
qiime phylogeny align-to-tree-mafft-fasttree \
  --i-sequences rep-seqs.qza \
  --o-alignment aligned-rep-seqs.qza \
  --o-masked-alignment masked-aligned-rep-seqs.qza \
  --o-tree unrooted-tree.qza \
  --o-rooted-tree rooted-tree.qza

qiime diversity alpha-rarefaction \
  --i-table control-filtered-table.qza \
  --i-phylogeny rooted-tree.qza \
  --p-max-depth 4000 \
  --m-metadata-file replicate-metadata-gnoto.txt \
  --o-visualization control-alpha-rarefaction.qzv

qiime diversity alpha-rarefaction \
  --i-table cecal-filtered-table.qza \
  --i-phylogeny rooted-tree.qza \
  --p-max-depth 10000 \
  --m-metadata-file replicate-metadata-gnoto.txt \
  --o-visualization cecal-alpha-rarefaction.qzv

qiime diversity alpha-rarefaction \
  --i-table fecal-filtered-table.qza \
  --i-phylogeny rooted-tree.qza \
  --p-max-depth 8903 \
  --m-metadata-file replicate-metadata-gnoto.txt \
  --o-visualization fecal-alpha-rarefaction.qzv

#Need to alter p-max-depth
qiime diversity alpha-rarefaction \
  --i-table donor-filtered-table.qza \
  --i-phylogeny rooted-tree.qza \
  --p-max-depth 9424 \
  --m-metadata-file replicate-metadata-gnoto.txt \
  --o-visualization donor-alpha-rarefaction.qzv

echo "End time"
date +"%d %B %Y %H:%M:%S"

