#!/bin/sh -l

#SBATCH --nodes=1                   
#SBATCH -n 20                        
#SBATCH --time=04:00:00             
#SBATCH --job-name Mouse-ASVTable       
#SBATCH -A microbiome                

echo "Start time"
date +"%d %B %Y %H:%M:%S"

#step 1, cd into the proper directory. This directory must already exist

cd $RCAC_SCRATCH
cd ANSC516_MouseData/Data_Import

pwd

#step 2, Load Modules

echo "loading bioinfo"
module load bioinfo

echo "loading qiime2-2023.9"
module load Qiime/2-2023.9

echo "initiating qiime2 Pig2Mouse Filtering"

qiime feature-table filter-samples \
  --i-table table.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --p-where "[sample-type]='cecal'" \
  --o-filtered-table cecal-filtered-table.qza

qiime feature-table filter-samples \
  --i-table table.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --p-where "[sample-type]='fecal'" \
  --o-filtered-table fecal-filtered-table.qza

qiime feature-table filter-samples \
  --i-table table.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --p-where "[sample-type]='Control'" \
  --o-filtered-table control-filtered-table.qza

#Create a .qzv from the output of denoise
qiime feature-table summarize \
  --i-table cecal-filtered-table.qza \
  --o-visualization cecal-filtered-table.qzv \
  --m-sample-metadata-file manifest-notab.txt

qiime feature-table summarize \
  --i-table fecal-filtered-table.qza \
  --o-visualization fecal-filtered-table.qzv \
  --m-sample-metadata-file manifest-notab.txt

qiime feature-table summarize \
  --i-table control-filtered-table.qza \
  --o-visualization control-filtered-table.qzv \
  --m-sample-metadata-file metadata-gnoto.txt

echo "End time"
date +"%d %B %Y %H:%M:%S"
