#!/bin/sh -l

#SBATCH --nodes=1                   
#SBATCH -n 20                        
#SBATCH --time=10:00:00              
#SBATCH --job-name Diversity-Control-Pipeline       
#SBATCH -A microbiome

echo "Start time"
date +"%d %B %Y %H:%M:%S"

cd $RCAC_SCRATCH
cd ANSC516_MouseData/Control

pwd

echo "loading bioinfo"
module load bioinfo

echo "loading qiime2-2023.9"
module load Qiime/2-2023.9

echo "initiating qiime2 diversity pipeline"

#Calculate diversity metrics. You will need to designate a sampling depth. You might want to consult the rarifaction output prior to this step.
qiime diversity core-metrics-phylogenetic \
  --i-phylogeny rooted-tree.qza \
  --i-table control-filtered-table.qza \
  --p-sampling-depth 2550 \
  --m-metadata-file updated-metadata-gnoto.txt \
  --output-dir control-core-metrics-results

#Statistical testing
qiime diversity alpha-group-significance \
  --i-alpha-diversity control-core-metrics-results/faith_pd_vector.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --o-visualization control-core-metrics-results/faith-pd-group-significance.qzv

qiime diversity alpha-group-significance \
  --i-alpha-diversity control-core-metrics-results/evenness_vector.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --o-visualization control-core-metrics-results/evenness-group-significance.qzv

qiime diversity alpha-group-significance \
  --i-alpha-diversity control-core-metrics-results/shannon_vector.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --o-visualization control-core-metrics-results/shannon-group-significance.qzv

qiime diversity alpha-group-significance \
  --i-alpha-diversity control-core-metrics-results/observed_features_vector.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --o-visualization control-core-metrics-results/observed_features-group-significance.qzv

qiime diversity beta-group-significance \
  --i-distance-matrix control-core-metrics-results/unweighted_unifrac_distance_matrix.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --m-metadata-column donor_type \
  --o-visualization control-core-metrics-results/unweighted-unifrac-donor-type-significance.qzv \
  --p-pairwise

qiime diversity beta-group-significance \
  --i-distance-matrix control-core-metrics-results/unweighted_unifrac_distance_matrix.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --m-metadata-column donor_type \
  --o-visualization control-core-metrics-results/unweighted-unifrac-donor-type-significance.qzv \
  --p-pairwise

#Make ordination
qiime emperor plot \
  --i-pcoa control-core-metrics-results/unweighted_unifrac_pcoa_results.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --p-custom-axes donor_type \
  --o-visualization control-core-metrics-results/unweighted-unifrac-emperor-donor-type.qzv

qiime emperor plot \
  --i-pcoa control-core-metrics-results/bray_curtis_pcoa_results.qza \
  --m-metadata-file updated-metadata-gnoto.txt \
  --p-custom-axes donor_type \
  --o-visualization control-core-metrics-results/bray-curtis-emperor-donor-type.qzv

echo "Classify and get .qzv"
qiime feature-classifier classify-sklearn \
  --i-classifier gg-13-8-99-515-806-nb-classifier.qza \
  --i-reads rep-seqs.qza \
  --o-classification taxonomy.qza

qiime metadata tabulate \
  --m-input-file taxonomy.qza \
  --o-visualization taxonomy.qzv

echo "End time"
date +"%d %B %Y %H:%M:%S"

